// <auto-generated />
namespace DagelijkseInname.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _23042017342 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_23042017342));
        
        string IMigrationMetadata.Id
        {
            get { return "201704231343194_23.04.2017.342"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
